name: Build Docker Image For RFC Compilation

on:
  push:
    branches: ['main']
    paths:
      - 'tools/Dockerfile'
      - 'tools/docker.version'
      - 'tools/puppeteer-config.json'
      - '.github/workflows/build-docker.yml'
  pull_request:
    paths:
      - 'tools/Dockerfile'
      - 'tools/docker.version'
      - 'tools/puppeteer-config.json'
      - '.github/workflows/build-docker.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    env:
      package-name: "ghcr.io/org-zpr/rfc-build"
    steps:
      - name: Log in to the Container registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: version
        working-directory: "./tools/"
        shell: bash
        run: echo "version=$(cat docker.version)" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: "./tools/"
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.package-name }}:latest
            ${{ env.package-name }}:${{ steps.version.outputs.version }}
